trigger:
- main

variables:
  azureSubscription: 'azure-service-connection'
  webAppNameDev: 'webapp-dev-2468'
  webAppNameStaging: 'webapp-staging-2468'
  webAppNameProd: 'webapp-prod-2468'

stages:
- stage: Build
  displayName: 'Continuous Integration (CI)'
  jobs:
  - job: BuildFullStack
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: NodeTool@0
      inputs:
        versionSpec: '22.x'
    - script: |
        npm install
        npm run build
      workingDirectory: 'frontend-react'
      displayName: 'Compile React SPA'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*Tests/*.csproj'
        arguments: '--configuration Release'
      displayName: 'Run Unit Tests (xUnit)'

    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/drop'
      displayName: 'Publish .NET Backend'

    - task: CopyFiles@2
      inputs:
        SourceFolder: 'frontend-react/dist'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/drop/wwwroot'
      displayName: 'Merge React into .NET wwwroot'

    - publish: '$(Build.ArtifactStagingDirectory)/drop'
      artifact: drop

- stage: DeployDev
  displayName: 'Deploy to Development'
  dependsOn: Build
  jobs:
  - deployment: Deploy
    environment: 'Development'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: $(webAppNameDev)
              package: '$(Pipeline.Workspace)/drop'

- stage: DeployStaging
  displayName: 'Deploy to Staging'
  dependsOn: DeployDev
  jobs:
  - deployment: Deploy
    environment: 'Staging'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: $(webAppNameStaging)
              package: '$(Pipeline.Workspace)/drop'

- stage: DeployProd
  displayName: 'Deploy to Production (GATED)'
  dependsOn: DeployStaging
  jobs:
  - deployment: Deploy
    environment: 'Production'
    pool:
      vmImage: 'ubuntu-latest'
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            inputs:
              azureSubscription: $(azureSubscription)
              appType: 'webAppLinux'
              appName: $(webAppNameProd)
              package: '$(Pipeline.Workspace)/drop'