using Serilog;
using Serilog.Formatting.Compact;

// 1. Initialize Compact JSON Logger (Azure Monitor Ready)
Log.Logger = new LoggerConfiguration()
    .WriteTo.Console(new CompactJsonFormatter())
    .CreateLogger();

try
{
    Log.Information("Starting web application initialization");
    var builder = WebApplication.CreateBuilder(args);

    // Override native logging with Serilog provider
    builder.Host.UseSerilog(); 

    // 2. Inject Native Health Check Modules
    builder.Services.AddHealthChecks();

    // 3. Configure CORS (Cross-Origin Resource Sharing)
    // This allows your React frontend (on port 5173) to securely talk to this API
    builder.Services.AddCors(options => 
    {
        options.AddPolicy("AllowAll", 
            policy => policy.AllowAnyOrigin()
                            .AllowAnyMethod()
                            .AllowAnyHeader());
    });

    var app = builder.Build();

    // 4. Activate the CORS policy
    // CRITICAL: This must go exactly here, BEFORE UseRouting and MapGet
    app.UseCors("AllowAll");

    app.UseRouting();

    // 5. Map Health Check Route for Azure Load Balancers
    app.MapHealthChecks("/health");

    // 6. Map the Status API Route that React fetches
    app.MapGet("/api/status", (IConfiguration config) =>
    {
        var envName = config.GetValue<string>("AppConfig:EnvironmentName") ?? "Unknown";
        var version = config.GetValue<string>("AppConfig:Version") ?? "0.0.0";

        Log.Information("Status endpoint pinged. Current Environment: {Environment}", envName);

        return Results.Ok(new 
        { 
            Status = "Operational", 
            ActiveEnvironment = envName,
            AppVersion = version,
            Timestamp = DateTime.UtcNow 
        });
    });

    // 7. Map the Enterprise Dictionary API Route
    // This is the new endpoint that feeds your Live Search React UI!
    app.MapGet("/api/dictionary", () =>
    {
        var dictionaryData = new[]
        {
            new { word = "Artifact", partOfSpeech = "n.", definition = "A compiled, deployable package of code, such as a .zip file, generated by a CI pipeline." },
            new { word = "Pipeline", partOfSpeech = "n.", definition = "An automated sequence of stages (Build, Test, Deploy) that code travels through to reach production." },
            new { word = "Immutable", partOfSpeech = "adj.", definition = "A principle where deployment packages or servers are never modified after creation; they are fully replaced instead." },
            new { word = "Telemetry", partOfSpeech = "n.", definition = "The automated collection of data, such as logs and metrics, from live remote systems." },
            new { word = "Configuration Drift", partOfSpeech = "n.", definition = "The phenomenon where server environments gradually become different from their original, documented setup due to manual changes." }
        };

        return Results.Ok(dictionaryData);
    });

    // 8. Serve React Frontend
    // This tells .NET to look for your React files and serve them to the browser
    app.UseDefaultFiles();
    app.UseStaticFiles();
    app.MapFallbackToFile("index.html");

    Log.Information("Application booted successfully. Ready for traffic.");
    app.Run();
}
catch (Exception ex)
{
    Log.Fatal(ex, "Application terminated unexpectedly");
}
finally
{
    Log.CloseAndFlush();
}